todo/urls.py
from django.urls import path
from . import views

app_name = 'todo'

urlpatterns = [
    path('add/', views.add, name='add'),
    path('', views.list, name='home'),
    path('delete/<int:id>', views.delete, name = 'delete')
]

todo_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo/', include('todo.urls')),
]

todo/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.
class ToDoItem(models.Model):
    title = models.CharField(max_length=50)
    todo_text = models.CharField(max_length = 500)
    condition = models.BooleanField(default=False)
    #piority = models.BooleanField()
    creation_time = models.DateTimeField(auto_now_add=True)
    #user = models.ForeignKey(User,on_delete = models.CASCADE )

    def __str__(self):
        return self.title
    

todo/views.py
from django.shortcuts import render, redirect
from . import models
from django.urls import reverse

# Create your views here.
def add(request):
    if request.POST:
        creation_time = ''
        title = request.POST['title']
        todo_text = request.POST['todo_text']
        #piority = request.POST['piority']
        condition = False
        #user = User
        creation_time = creation_time
        models.ToDoItem.objects.create(title=title,todo_text=todo_text, condition=condition, creation_time=creation_time)
        return redirect(reverse('todo:home'))
    else:
        return render(request, 'todo/add.html')

def list(request):
    all_todoitems = models.ToDoItem.objects.all()
    context = {'all_todoitems': all_todoitems}
    return render(request, 'todo/home.html', context=context)
    
def delete(request):
    if request.POST:
        id = request.POST['id']
        try:
            models.ToDoItem.objects.get(id=id).delete()
            return redirect(reverse('todo:home'))
        except:
            print('wrong id')
            return redirect(reverse('todo:home'))
        else:
            return render(request, 'todo/delete.html')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>

    <title>ToDo List</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a class="nav-link active" aria-current="page" href="{% url 'todo:home' %}">Home</a>
              <a class="nav-link" href="{% url 'todo:add' %}">Add 'ToDo' Item</a>
            </div>
          </div>
        </div>
      </nav>
{%block content%}

{% endblock %}
</body>
</html>

todo/templates/todo/add.html
{% extends "base.html" %}

{% block content %}
  <form action='' method = 'POST'>
    {% csrf_token %}
    <div class="form-group">
      <label for="title" class="form-label">Title:</label>
      <div class="col-sm-10">
        <input type="text" class="form-control" id="title", name='title'>
      </div>
    </div>
    <div class="form-group">
      <label for="todo_text" class="form-label">ToDo:</label>
      <textarea class="form-control" id="todo_text", name = 'todo_text', rows="4"></textarea>
    </div>
    <fieldset class="row mb-3">
      <legend class="col-form-label col-sm-2 pt-0">Piority</legend>
      <div class="col-sm-10">
        <div class="form-check">
          <input class="form-check-input" type="checkbox" value="" id="piority">
          <label class="form-check-label" for="piority">
            Important
          </label>
        </div>
      </div>
    </fieldset>
    <button type="submit" class="btn btn-primary">Sign in</button>
  </form>
{% endblock %}

todo/templates/todo/home.html
{% extends "base.html" %}

{% block content %}
<div class="'container">
    <h1>home.html</h1>
        {% for task in all_todoitems %}
        <div class='row'>
            <div class='col-md-6' style = 'margin:0 auto;'>
                <div class="card" style="width: 18rem; margin-top: 1rem;">
                    <div class="card-body">
                      <h5 class="card-title">{{task.title}}</h5>
                      <p class="card-text">{{task.todo_text}}</p>
                      <p class="card-text">{{task.creation_time}}</p>
                      <a href="#" class="btn btn-primary">Go somewhere</a>
                    </div>
                  </div>  
            </div>
        </div>
        {% endfor %}
</div>>
{% endblock %}